# Generated by Django 4.2.20 on 2025-04-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presta',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presta',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presta',
            name='localisation',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='presta',
            name='numero',
            field=models.CharField(max_length=255),
        ),
    ]
