# Generated by Django 4.2.20 on 2025-03-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presta',
            name='localisation',
            field=models.CharField(default='https://www.google.com/maps/dir/?api=1&destination=Super+U+Bali,+Douala,+Cameroun&travelmode=driving', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presta',
            name='numero',
            field=models.CharField(default=678910123, max_length=9),
            preserve_default=False,
        ),
    ]
