# Generated by Django 4.2.20 on 2025-03-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presta', '0002_presta_localisation_presta_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presta',
            old_name='localisation',
            new_name='Telephone',
        ),
        migrations.RemoveField(
            model_name='presta',
            name='numero',
        ),
    ]
