# Generated by Django 4.2.20 on 2025-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presta', '0003_rename_localisation_presta_telephone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presta',
            name='Telephone',
        ),
        migrations.AddField(
            model_name='presta',
            name='numero',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
