# Generated by Django 4.2.20 on 2025-03-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presta', '0004_remove_presta_telephone_presta_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='presta',
            name='localisation',
            field=models.TextField(default='https://www.google.com/maps/dir/?api=1&destination=Super+U+Bali,+Douala,+Cameroun&travelmode=driving', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presta',
            name='numero',
            field=models.TextField(max_length=255),
        ),
    ]
