# Generated by Django 4.2.20 on 2025-03-28 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('numero', models.TextField(max_length=255)),
                ('localisation', models.TextField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prestataire',
                'verbose_name_plural': 'Prestataires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PrestaModificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('presta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presta.presta')),
            ],
            options={
                'verbose_name': 'Log de modification',
                'verbose_name_plural': 'Logs de modifications',
                'ordering': ['-timestamp'],
            },
        ),
    ]
